# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - emotionapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://emotionapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3feb0faa836f4d2188040ba107958cff }}
        password: ${{ secrets.AzureAppService_ContainerPassword_50f14588935e45c3800c73bcbb4dba71 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: emotionapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3feb0faa836f4d2188040ba107958cff }}/emotionapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'emotionapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_304dcafe24ce43e487bd4a1c8ac38783 }}
        images: 'emotionapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3feb0faa836f4d2188040ba107958cff }}/emotionapp:${{ github.sha }}'